version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.13.0
    container_name: selenium-hub
    environment:
      - SE_ENABLE_TRACING=false
      - SE_GRID_MAX_SESSION=5
      - SE_GRID_SESSION_TIMEOUT=60
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    
  chrome:
    image: selenium/node-chrome:4.13.0
    shm_size: 2gb
    platform: linux/amd64
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false

  onlinevoting_migrate:
    image: shinsenter/codeigniter4:dev-php8.2
    container_name: codeigniter_migrate
    volumes:
      - .:/var/www/html
    command: php spark migrate
    environment:
      - CI_ENVIRONMENT=development

  onlinevoting_app:
    image: shinsenter/codeigniter4:dev-php8.2
    container_name: codeigniter_app
    ports:
      - "8080:80"
      - "4430:443"
    volumes:
      - .:/var/www/html
    environment:
      - app.baseURL = 'http://localhost:8080/'
      - CI_ENVIRONMENT=development

  onlinevoting_db:
    image: mysql:8.0
    container_name: codeigniter_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlinevoting
      MYSQL_USER: codeigniter
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
