version: '3.8'

services:
  migrate:
    image: shinsenter/codeigniter4:dev-php8.2
    container_name: codeigniter_migrate
    volumes:
      - .:/var/www/html
    command: php spark migrate
    environment:
      - CI_ENV=development
  app:
    image: shinsenter/codeigniter4:dev-php8.2
    container_name: codeigniter_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    environment:
      - CI_ENV=development

volumes:
  db_data:
